const processCo2 = require('./processCo2')
const processSeaIce = require('./processSeaIce')
const processTemps = require('./processTemps')
const processForest = require('./processForest')
const processSealevel = require('./processSeaLevel')
const processPopulation = require('./processPopulation')
const processLiveStock = require('./processLifeStock')

// processTemps()
// processCo2()
// processForest()
// processSealevel() 
// processPopulation()
processLiveStock()